apiVersion: apps/v1
kind: Deployment
metadata:
  name: okxeel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okxeel
  template:
    metadata:
      labels:
        app: okxeel
    spec:
      containers:
        - name: okxeel
          image: bucha1958/okxeel:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: okxeel-config
---
apiVersion: v1
kind: Service
metadata:
  name: okxeel-service
spec:
  selector:
    app: okxeel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
