name: Okxeel Service CI

on:
  push:
    paths:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set commit date as image tag
        id: tag
        run: |
          DATE_TAG=$(date -u +"%Y-%m-%d-%H%M")
          echo "tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_CONTENT }}" > .env

      - name: Build and tag Docker image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL=http://3.249.15.91 \
            --build-arg VITE_AUTH_SERVICE_URL=http://3.249.15.91 \
            -t ${{ secrets.DOCKER_USERNAME }}/okxeel:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/okxeel:${{ steps.tag.outputs.tag }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/okxeel:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/okxeel:${{ steps.tag.outputs.tag }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/ --validate=false

      - name: Force restart frontend deployment
        run: kubectl rollout restart deployment okxeel-deployment
